version: "3"
services:
  app:
    build: .
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NODE_ENV: development
      PORT: "${PORT}"

    ports:
      - "${PORT}:${PORT}"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
